version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: vg411
      MYSQL_DATABASE: myDB
      LANG: C.UTF-8
    volumes:
      - "./data:/var/lib/mysql:rw"

  web:
    build: .
    command: uwsgi uwsgi.ini
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - "./data:/var/lib/redis:rw"
