version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: vg411
      MYSQL_DATABASE: myDB
      LANG: C.UTF-8
    volumes:
      - "./data:/var/lib/mysql:rw"
  web:
    build: .
    command: uwsgi uwsgi.ini
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
