version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: vg411
      MYSQL_DATABASE: myDB
      LANG: C.UTF-8
    volumes:
      - "./data:/var/lib/mysql:rw"

  web:
    build: .
    volumes:
      - .:/code
      - ./staticfiles/:/static
    expose:
      - 8000
    depends_on:
      - db
      - redis
    command: daphne -b 0.0.0.0 -p 8000 veryGoodSite.asgi:application
    # command: gunicorn veryGoodSite.wsgi:application --bind 0.0.0.0:8000 

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles/:/static
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - "./data:/var/lib/redis:rw"
